import { ProjectData, FrameData, FrameType, FramePoint, ExportLanguage, FrameAnchor, ExportVersion } from '../types';
import { createDefaultAnchors } from './anchorUtils';

// API 前缀映射
const API_PREFIX = {
  reforged: 'Blz',
  '1.27': 'Dz',
} as const;

// 获取 API 函数�?
function getAPIFunction(version: ExportVersion, funcName: string): string {
  const prefix = API_PREFIX[version];
  return `${prefix}${funcName}`;
}

// �?FramePoint 枚举转换�?WC3 常量名称
function framePointToString(point: FramePoint): string {
  const pointNames = [
    'FRAMEPOINT_TOPLEFT',
    'FRAMEPOINT_TOP',
    'FRAMEPOINT_TOPRIGHT',
    'FRAMEPOINT_LEFT',
    'FRAMEPOINT_CENTER',
    'FRAMEPOINT_RIGHT',
    'FRAMEPOINT_BOTTOMLEFT',
    'FRAMEPOINT_BOTTOM',
    'FRAMEPOINT_BOTTOMRIGHT',
  ];
  return pointNames[point] || 'FRAMEPOINT_BOTTOMLEFT';
}

// 生成锚点设置代码 (JASS)
function generateAnchorsJASS(frameName: string, anchors: FrameAnchor[], version: ExportVersion): string {
  let code = '';
  const setPoint = getAPIFunction(version, 'FrameSetPoint');
  const setAbsPoint = getAPIFunction(version, 'FrameSetAbsPoint');
  
  for (const anchor of anchors) {
    const anchorPoint = framePointToString(anchor.point);
    if (anchor.relativeTo && anchor.relativePoint !== undefined) {
      // 相对定位
      const relativePoint = framePointToString(anchor.relativePoint);
      code += `    call ${setPoint}(${frameName}, ${anchorPoint}, ${anchor.relativeTo}, ${relativePoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)})\n`;
    } else {
      // 绝对定位
      code += `    call ${setAbsPoint}(${frameName}, ${anchorPoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)})\n`;
    }
  }
  return code;
}

// 生成锚点设置代码 (LUA)
function generateAnchorsLUA(frameName: string, anchors: FrameAnchor[], version: ExportVersion): string {
  let code = '';
  const setPoint = getAPIFunction(version, 'FrameSetPoint');
  const setAbsPoint = getAPIFunction(version, 'FrameSetAbsPoint');
  
  for (const anchor of anchors) {
    const anchorPoint = framePointToString(anchor.point);
    if (anchor.relativeTo && anchor.relativePoint !== undefined) {
      // 相对定位
      const relativePoint = framePointToString(anchor.relativePoint);
      code += `    ${setPoint}(${frameName}, ${anchorPoint}, ${anchor.relativeTo}, ${relativePoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)})\n`;
    } else {
      // 绝对定位
      code += `    ${setAbsPoint}(${frameName}, ${anchorPoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)})\n`;
    }
  }
  return code;
}

// 生成锚点设置代码 (TypeScript)
function generateAnchorsTypeScript(frameName: string, anchors: FrameAnchor[], version: ExportVersion): string {
  let code = '';
  const setPoint = getAPIFunction(version, 'FrameSetPoint');
  const setAbsPoint = getAPIFunction(version, 'FrameSetAbsPoint');
  
  for (const anchor of anchors) {
    const anchorPoint = framePointToString(anchor.point);
    if (anchor.relativeTo && anchor.relativePoint !== undefined) {
      // 相对定位
      const relativePoint = framePointToString(anchor.relativePoint);
      code += `    ${setPoint}(this.${frameName}, ${anchorPoint}, ${anchor.relativeTo}, ${relativePoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)});\n`;
    } else {
      // 绝对定位
      code += `    ${setAbsPoint}(this.${frameName}, ${anchorPoint}, ${anchor.x.toFixed(5)}, ${anchor.y.toFixed(5)});\n`;
    }
  }
  return code;
}

// JASS 代码模板
const JASS_TEMPLATES = {
  header: (libName: string) => `
//===========================================================================
// UI Library: ${libName}
// Generated by Warcraft 3 UI Designer
// Date: ${new Date().toLocaleString()}
//===========================================================================

library ${libName} initializer Init

globals
`,
  
  frameDeclaration: (name: string, isArray: boolean) => 
    isArray 
      ? `    framehandle array ${name}\n`
      : `    framehandle ${name} = null\n`,
  
  endGlobals: `endglobals

function CreateFrames takes nothing returns nothing
`,
  
  createBackdrop: (name: string, _parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, texture: string) => `
    set ${name} = BlzCreateFrame("BACKDROP", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
    call BlzFrameSetTexture(${name}, "${texture}", 0, true)
`,
  
  createButton: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number) => `
    set ${name} = BlzCreateFrame("ScriptDialogButton", ${parent}, 0, 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
`,
  
  createText: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, text: string, scale: number, color: string) => `
    set ${name} = BlzCreateFrameByType("TEXT", "", ${parent}, "", 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
    call BlzFrameSetText(${name}, "|cff${color.slice(1)}${text}|r")
    call BlzFrameSetScale(${name}, ${scale.toFixed(2)})
`,

  createEditBox: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, _multiline: boolean) => `
    set ${name} = BlzCreateFrameByType("EDITBOX", "", ${parent}, "", 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
    call BlzFrameSetEnable(${name}, true)
    call BlzFrameSetFocus(${name}, false)
`,

  createSlider: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, minValue: number, maxValue: number, stepSize: number) => `
    set ${name} = BlzCreateFrame("SliderTemplate", ${parent}, 0, 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
    call BlzFrameSetMinMaxValue(${name}, ${minValue.toFixed(2)}, ${maxValue.toFixed(2)})
    call BlzFrameSetStepSize(${name}, ${stepSize.toFixed(2)})
`,

  createCheckBox: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, checked: boolean) => `
    set ${name} = BlzCreateFrame("CheckBoxTemplate", ${parent}, 0, 0)
    call BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
    call BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
    call BlzFrameSetEnable(${name}, ${checked ? 'true' : 'false'})
`,
  
  footer: (_libName: string) => `
endfunction

function Init takes nothing returns nothing
    call CreateFrames()
endfunction

endlibrary
`
};

// LUA 代码模板
const LUA_TEMPLATES = {
  header: (libName: string) => `
--===========================================================================
-- UI Library: ${libName}
-- Generated by Warcraft 3 UI Designer
-- Date: ${new Date().toLocaleString()}
--===========================================================================

${libName} = {}
`,
  
  frameDeclaration: (name: string, isArray: boolean) => 
    isArray 
      ? `${name} = {}\n`
      : `${name} = nil\n`,
  
  createBackdrop: (name: string, _parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, texture: string) => `
${name} = BlzCreateFrame("BACKDROP", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 0, 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
BlzFrameSetTexture(${name}, "${texture}", 0, true)
`,
  
  createButton: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number) => `
${name} = BlzCreateFrame("ScriptDialogButton", ${parent}, 0, 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
`,
  
  createText: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, text: string, scale: number, color: string) => `
${name} = BlzCreateFrameByType("TEXT", "", ${parent}, "", 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
BlzFrameSetText(${name}, "|cff${color.slice(1)}${text}|r")
BlzFrameSetScale(${name}, ${scale.toFixed(2)})
`,

  createEditBox: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, _multiline: boolean) => `
${name} = BlzCreateFrameByType("EDITBOX", "", ${parent}, "", 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
BlzFrameSetEnable(${name}, true)
BlzFrameSetFocus(${name}, false)
`,

  createSlider: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, minValue: number, maxValue: number, stepSize: number) => `
${name} = BlzCreateFrame("SliderTemplate", ${parent}, 0, 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
BlzFrameSetMinMaxValue(${name}, ${minValue.toFixed(2)}, ${maxValue.toFixed(2)})
BlzFrameSetStepSize(${name}, ${stepSize.toFixed(2)})
`,

  createCheckBox: (name: string, parent: string, anchorPoint: string, x: number, y: number, width: number, height: number, checked: boolean) => `
${name} = BlzCreateFrame("CheckBoxTemplate", ${parent}, 0, 0)
BlzFrameSetAbsPoint(${name}, ${anchorPoint}, ${x.toFixed(5)}, ${y.toFixed(5)})
BlzFrameSetSize(${name}, ${width.toFixed(5)}, ${height.toFixed(5)})
BlzFrameSetEnable(${name}, ${checked ? 'true' : 'false'})
`,
  
  footer: () => ``
};

// 生成 JASS 代码
export function generateJASSCode(project: ProjectData): string {
  const version = project.exportVersion || 'reforged';
  let code = JASS_TEMPLATES.header(project.libraryName);
  
  // 声明所�?Frame 变量
  Object.values(project.frames).forEach(frame => {
    const isArray = frame.name.includes('[');
    if (!isArray || frame.name.includes('[00]')) {
      const varName = isArray ? frame.name.replace('[00]', '') : frame.name;
      code += JASS_TEMPLATES.frameDeclaration(varName, isArray);
    }
  });
  
  code += JASS_TEMPLATES.endGlobals;
  
  // 创建所�?Frame
  Object.values(project.frames).forEach(frame => {
    code += generateFrameJASS(frame, project, version);
  });
  
  // 添加通用设置
  if (project.hideGameUI) {
    const enableAutoPos = getAPIFunction(version, 'EnableUIAutoPosition');
    const hideOriginFrames = getAPIFunction(version, 'HideOriginFrames');
    code += `    call ${enableAutoPos}(false)\n`;
    code += `    call ${hideOriginFrames}(true)\n`;
  }
  
  code += JASS_TEMPLATES.footer(project.libraryName);
  
  return code;
}

// 生成 LUA 代码
export function generateLUACode(project: ProjectData): string {
  const version = project.exportVersion || 'reforged';
  let code = LUA_TEMPLATES.header(project.libraryName);
  
  code += '\n-- Frame declarations\n';
  Object.values(project.frames).forEach(frame => {
    const isArray = frame.name.includes('[');
    if (!isArray || frame.name.includes('[00]')) {
      const varName = isArray ? frame.name.replace('[00]', '') : frame.name;
      code += LUA_TEMPLATES.frameDeclaration(varName, isArray);
    }
  });
  
  code += '\nfunction CreateFrames()\n';
  
  // 创建所�?Frame
  Object.values(project.frames).forEach(frame => {
    code += generateFrameLUA(frame, project, version);
  });
  
  // 添加通用设置
  if (project.hideGameUI) {
    const enableAutoPos = getAPIFunction(version, 'EnableUIAutoPosition');
    const hideOriginFrames = getAPIFunction(version, 'HideOriginFrames');
    code += `    ${enableAutoPos}(false)\n`;
    code += `    ${hideOriginFrames}(true)\n`;
  }
  
  code += 'end\n\n';
  code += 'CreateFrames()\n';
  
  return code;
}

// 生成单个 Frame �?JASS 代码
function generateFrameJASS(frame: FrameData, project: ProjectData, version: ExportVersion): string {
  const parent = frame.parentId ? project.frames[frame.parentId].name : `${getAPIFunction(version, 'GetOriginFrame')}(ORIGIN_FRAME_GAME_UI, 0)`;
  
  // 获取锚点数组,如果不存在则创建默认锚点
  const anchors = frame.anchors || createDefaultAnchors(frame.x, frame.y, frame.width, frame.height);
  
  const createFrame = getAPIFunction(version, 'CreateFrame');
  const createFrameByType = getAPIFunction(version, 'CreateFrameByType');
  const frameSetSize = getAPIFunction(version, 'FrameSetSize');
  const frameSetTexture = getAPIFunction(version, 'FrameSetTexture');
  const frameSetText = getAPIFunction(version, 'FrameSetText');
  const frameSetScale = getAPIFunction(version, 'FrameSetScale');
  const frameSetEnable = getAPIFunction(version, 'FrameSetEnable');
  const frameSetFocus = getAPIFunction(version, 'FrameSetFocus');
  const frameSetMinMaxValue = getAPIFunction(version, 'FrameSetMinMaxValue');
  const frameSetStepSize = getAPIFunction(version, 'FrameSetStepSize');
  
  let code = '';
  
  switch (frame.type) {
    case FrameType.BACKDROP:
      code += `    set ${frame.name} = ${createFrame}("BACKDROP", ${parent}, 0, 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    call ${frameSetTexture}(${frame.name}, "${frame.texture || 'UI\\\\Widgets\\\\EscMenu\\\\Human\\\\background.blp'}", 0, true)\n`;
      break;
    
    case FrameType.BUTTON:
    case FrameType.BROWSER_BUTTON:
    case FrameType.SCRIPT_DIALOG_BUTTON:
      code += `    set ${frame.name} = ${createFrame}("ScriptDialogButton", ${parent}, 0, 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      break;
    
    case FrameType.TEXT_FRAME:
      code += `    set ${frame.name} = ${createFrameByType}("TEXT", "", ${parent}, "", 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    call ${frameSetText}(${frame.name}, "|cff${(frame.textColor || '#FFFFFF').slice(1)}${frame.text || ''}|r")\n`;
      code += `    call ${frameSetScale}(${frame.name}, ${(frame.textScale || 1).toFixed(2)})\n`;
      break;
    
    case FrameType.EDITBOX:
      code += `    set ${frame.name} = ${createFrameByType}("EDITBOX", "", ${parent}, "", 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    call ${frameSetEnable}(${frame.name}, true)\n`;
      code += `    call ${frameSetFocus}(${frame.name}, false)\n`;
      break;
    
    case FrameType.SLIDER:
      code += `    set ${frame.name} = ${createFrame}("SliderTemplate", ${parent}, 0, 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    call ${frameSetMinMaxValue}(${frame.name}, ${(frame.minValue || 0).toFixed(2)}, ${(frame.maxValue || 100).toFixed(2)})\n`;
      code += `    call ${frameSetStepSize}(${frame.name}, ${(frame.stepSize || 1).toFixed(2)})\n`;
      break;
    
    case FrameType.CHECKBOX:
      code += `    set ${frame.name} = ${createFrame}("CheckBoxTemplate", ${parent}, 0, 0)\n`;
      code += generateAnchorsJASS(frame.name, anchors, version);
      code += `    call ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    call ${frameSetEnable}(${frame.name}, ${frame.checked ? 'true' : 'false'})\n`;
      break;
    
    default:
      code += `    // TODO: Implement ${FrameType[frame.type]}\n`;
      break;
  }
  
  code += '\n';
  return code;
}

// 生成单个 Frame �?LUA 代码
function generateFrameLUA(frame: FrameData, project: ProjectData, version: ExportVersion): string {
  const parent = frame.parentId ? project.frames[frame.parentId].name : `${getAPIFunction(version, 'GetOriginFrame')}(ORIGIN_FRAME_GAME_UI, 0)`;
  
  // 获取锚点数组,如果不存在则创建默认锚点
  const anchors = frame.anchors || createDefaultAnchors(frame.x, frame.y, frame.width, frame.height);
  
  const createFrame = getAPIFunction(version, 'CreateFrame');
  const createFrameByType = getAPIFunction(version, 'CreateFrameByType');
  const frameSetSize = getAPIFunction(version, 'FrameSetSize');
  const frameSetTexture = getAPIFunction(version, 'FrameSetTexture');
  const frameSetText = getAPIFunction(version, 'FrameSetText');
  const frameSetScale = getAPIFunction(version, 'FrameSetScale');
  const frameSetEnable = getAPIFunction(version, 'FrameSetEnable');
  const frameSetFocus = getAPIFunction(version, 'FrameSetFocus');
  const frameSetMinMaxValue = getAPIFunction(version, 'FrameSetMinMaxValue');
  const frameSetStepSize = getAPIFunction(version, 'FrameSetStepSize');
  
  let code = '';
  
  switch (frame.type) {
    case FrameType.BACKDROP:
      code += `    ${frame.name} = ${createFrame}("BACKDROP", ${parent}, 0, 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    ${frameSetTexture}(${frame.name}, "${frame.texture || 'UI\\\\Widgets\\\\EscMenu\\\\Human\\\\background.blp'}", 0, true)\n`;
      break;
    
    case FrameType.BUTTON:
    case FrameType.BROWSER_BUTTON:
    case FrameType.SCRIPT_DIALOG_BUTTON:
      code += `    ${frame.name} = ${createFrame}("ScriptDialogButton", ${parent}, 0, 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      break;
    
    case FrameType.TEXT_FRAME:
      code += `    ${frame.name} = ${createFrameByType}("TEXT", "", ${parent}, "", 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    ${frameSetText}(${frame.name}, "|cff${(frame.textColor || '#FFFFFF').slice(1)}${frame.text || ''}|r")\n`;
      code += `    ${frameSetScale}(${frame.name}, ${(frame.textScale || 1).toFixed(2)})\n`;
      break;
    
    case FrameType.EDITBOX:
      code += `    ${frame.name} = ${createFrameByType}("EDITBOX", "", ${parent}, "", 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    ${frameSetEnable}(${frame.name}, true)\n`;
      code += `    ${frameSetFocus}(${frame.name}, false)\n`;
      break;
    
    case FrameType.SLIDER:
      code += `    ${frame.name} = ${createFrame}("SliderTemplate", ${parent}, 0, 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    ${frameSetMinMaxValue}(${frame.name}, ${(frame.minValue || 0).toFixed(2)}, ${(frame.maxValue || 100).toFixed(2)})\n`;
      code += `    ${frameSetStepSize}(${frame.name}, ${(frame.stepSize || 1).toFixed(2)})\n`;
      break;
    
    case FrameType.CHECKBOX:
      code += `    ${frame.name} = ${createFrame}("CheckBoxTemplate", ${parent}, 0, 0)\n`;
      code += generateAnchorsLUA(frame.name, anchors, version);
      code += `    ${frameSetSize}(${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)})\n`;
      code += `    ${frameSetEnable}(${frame.name}, ${frame.checked ? 'true' : 'false'})\n`;
      break;
    
    default:
      code += `    -- TODO: Implement ${FrameType[frame.type]}\n`;
      break;
  }
  
  code += '\n';
  return code;
}

// 生成 TypeScript 代码
export function generateTypeScriptCode(project: ProjectData): string {
  const version = project.exportVersion || 'reforged';
  let code = `
/**
 * UI Library: ${project.libraryName}
 * Generated by Warcraft 3 UI Designer
 * Date: ${new Date().toLocaleString()}
 * Version: ${version === 'reforged' ? 'Reforged' : '1.27'}
 */

export class ${project.libraryName} {
`;
  
  // 声明所�?Frame 变量
  Object.values(project.frames).forEach(frame => {
    const isArray = frame.name.includes('[');
    if (!isArray || frame.name.includes('[00]')) {
      const varName = isArray ? frame.name.replace('[00]', '') : frame.name;
      code += isArray 
        ? `  private ${varName}: framehandle[] = [];\n`
        : `  private ${varName}: framehandle | null = null;\n`;
    }
  });
  
  code += `\n  constructor() {\n`;
  code += `    this.createFrames();\n`;
  code += `  }\n\n`;
  
  code += `  private createFrames(): void {\n`;
  
  // 创建所�?Frame
  Object.values(project.frames).forEach(frame => {
    code += generateFrameTypeScript(frame, project, version);
  });
  
  code += `  }\n`;
  code += `}\n\n`;
  code += `// 初始化\n`;
  code += `const ui = new ${project.libraryName}();\n`;
  
  return code;
}

// 生成单个 Frame �?TypeScript 代码
function generateFrameTypeScript(frame: FrameData, project: ProjectData, version: ExportVersion): string {
  const getOriginFrame = getAPIFunction(version, 'GetOriginFrame');
  const parent = frame.parentId ? `this.${project.frames[frame.parentId].name}` : `${getOriginFrame}(ORIGIN_FRAME_GAME_UI, 0)`;
  
  // 获取锚点数组,如果不存在则创建默认锚点
  const anchors = frame.anchors || createDefaultAnchors(frame.x, frame.y, frame.width, frame.height);
  
  const createFrame = getAPIFunction(version, 'CreateFrame');
  const createFrameByType = getAPIFunction(version, 'CreateFrameByType');
  const frameSetSize = getAPIFunction(version, 'FrameSetSize');
  const frameSetTexture = getAPIFunction(version, 'FrameSetTexture');
  const frameSetText = getAPIFunction(version, 'FrameSetText');
  const frameSetEnable = getAPIFunction(version, 'FrameSetEnable');
  const frameSetFocus = getAPIFunction(version, 'FrameSetFocus');
  const frameSetMinMaxValue = getAPIFunction(version, 'FrameSetMinMaxValue');
  const frameSetStepSize = getAPIFunction(version, 'FrameSetStepSize');
  
  let code = `\n    // ${frame.name}\n`;
  
  switch (frame.type) {
    case FrameType.BACKDROP:
      code += `    this.${frame.name} = ${createFrame}("BACKDROP", ${parent}, 0, 0);\n`;
      code += generateAnchorsTypeScript(frame.name, anchors, version);
      code += `    ${frameSetSize}(this.${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)});\n`;
      if (frame.texture) {
        code += `    ${frameSetTexture}(this.${frame.name}, "${frame.texture}", 0, true);\n`;
      }
      break;
    
    case FrameType.TEXT_FRAME:
      code += `    this.${frame.name} = ${createFrameByType}("TEXT", "", ${parent}, "", 0);\n`;
      code += generateAnchorsTypeScript(frame.name, anchors, version);
      code += `    ${frameSetSize}(this.${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)});\n`;
      if (frame.text) {
        code += `    ${frameSetText}(this.${frame.name}, "|cff${frame.textColor?.slice(1) || 'FFFFFF'}${frame.text}|r");\n`;
      }
      break;
    
    case FrameType.EDITBOX:
      code += `    this.${frame.name} = ${createFrameByType}("EDITBOX", "", ${parent}, "", 0);\n`;
      code += generateAnchorsTypeScript(frame.name, anchors, version);
      code += `    ${frameSetSize}(this.${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)});\n`;
      code += `    ${frameSetEnable}(this.${frame.name}, true);\n`;
      code += `    ${frameSetFocus}(this.${frame.name}, false);\n`;
      break;
    
    case FrameType.SLIDER:
      code += `    this.${frame.name} = ${createFrame}("SliderTemplate", ${parent}, 0, 0);\n`;
      code += generateAnchorsTypeScript(frame.name, anchors, version);
      code += `    ${frameSetSize}(this.${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)});\n`;
      code += `    ${frameSetMinMaxValue}(this.${frame.name}, ${frame.minValue || 0}, ${frame.maxValue || 100});\n`;
      code += `    ${frameSetStepSize}(this.${frame.name}, ${frame.stepSize || 1});\n`;
      break;
    
    case FrameType.CHECKBOX:
      code += `    this.${frame.name} = ${createFrame}("CheckBoxTemplate", ${parent}, 0, 0);\n`;
      code += generateAnchorsTypeScript(frame.name, anchors, version);
      code += `    ${frameSetSize}(this.${frame.name}, ${frame.width.toFixed(5)}, ${frame.height.toFixed(5)});\n`;
      code += `    ${frameSetEnable}(this.${frame.name}, ${frame.checked || false});\n`;
      break;
    
    default:
      code += `    // TODO: Implement ${FrameType[frame.type]}\n`;
  }
  
  return code;
}

// 主导出函�?
export function exportProject(project: ProjectData, language: ExportLanguage): string {
  switch (language) {
    case 'jass':
      return generateJASSCode(project);
    case 'lua':
      return generateLUACode(project);
    case 'ts':
      return generateTypeScriptCode(project);
    default:
      throw new Error(`Unsupported language: ${language}`);
  }
}
