/**
 * FDF导出工具 - 将FrameData转换为FDF格式文本
 */

import { FrameData, FrameType, FramePoint } from '../types';

interface ExportOptions {
  indent?: string;
  includeComments?: boolean;
}

/**
 * 将FrameData数组导出为FDF格式文本
 */
export function exportToFDF(frames: FrameData[], options: ExportOptions = {}): string {
  const { indent = '    ', includeComments = true } = options;
  
  const lines: string[] = [];
  
  if (includeComments) {
    lines.push('// Generated by WC3 UI Designer');
    lines.push('// Frame Definition File');
    lines.push('');
  }
  
  // 只导出顶层Frame(没有parentId的)
  const topLevelFrames = frames.filter(f => !f.parentId);
  
  topLevelFrames.forEach((frame, index) => {
    if (index > 0) lines.push(''); // 顶层Frame之间空行
    exportFrame(frame, frames, lines, indent, 0);
  });
  
  return lines.join('\n');
}

/**
 * 导出单个Frame及其子Frame
 */
function exportFrame(
  frame: FrameData,
  allFrames: FrameData[],
  lines: string[],
  indent: string,
  level: number
): void {
  const ind = indent.repeat(level);
  
  // Frame定义开始 - 带INHERITS支持
  let frameHeader = `${ind}Frame "${getFrameTypeString(frame.type)}" "${frame.name}"`;
  
  // 添加 INHERITS [WITHCHILDREN] "Template"
  if (frame.fdfMetadata?.inherits) {
    frameHeader += ` INHERITS`;
    
    // 检查是否有继承的子控件（WITHCHILDREN）
    if (frame.fdfMetadata.inheritedChildrenIds && frame.fdfMetadata.inheritedChildrenIds.length > 0) {
      frameHeader += ` WITHCHILDREN`;
    }
    
    frameHeader += ` "${frame.fdfMetadata.inherits}"`;
  }
  
  frameHeader += ' {';
  lines.push(frameHeader);
  
  // SetAllPoints
  if (frame.anchors) {
    const hasSetAllPoints = checkSetAllPoints(frame.anchors);
    if (hasSetAllPoints) {
      const anchor = frame.anchors[0];
      if (anchor.relativeTo) {
        // 将ID转换为Frame名称
        const relativeFrame = allFrames.find(f => f.id === anchor.relativeTo);
        const relativeName = relativeFrame ? relativeFrame.name : anchor.relativeTo;
        lines.push(`${ind}${indent}SetAllPoints "${relativeName}",`);
      } else {
        lines.push(`${ind}${indent}SetAllPoints,`);
      }
    } else {
      // 导出单个锚点
      frame.anchors.forEach(anchor => {
        exportAnchor(anchor, allFrames, lines, ind + indent);
      });
    }
  }
  
  // Width和Height
  if (frame.width !== undefined) {
    lines.push(`${ind}${indent}Width ${formatNumber(frame.width)},`);
  }
  if (frame.height !== undefined) {
    lines.push(`${ind}${indent}Height ${formatNumber(frame.height)},`);
  }
  
  // Text相关
  if (frame.text !== undefined) {
    lines.push(`${ind}${indent}Text "${escapeString(frame.text)}",`);
  }
  if (frame.textScale !== undefined && frame.textScale !== 1) {
    lines.push(`${ind}${indent}TextScale ${formatNumber(frame.textScale)},`);
  }
  if (frame.textColor) {
    lines.push(`${ind}${indent}TextColor ${frame.textColor},`);
  }
  if (frame.horAlign && frame.horAlign !== 'left') {
    lines.push(`${ind}${indent}HorizontalAlignment "${frame.horAlign.toUpperCase()}",`);
  }
  if (frame.verAlign && frame.verAlign !== 'start') {
    lines.push(`${ind}${indent}VerticalAlignment "${frame.verAlign.toUpperCase()}",`);
  }
  
  // 纹理和Backdrop属性
  if (frame.diskTexture) {
    lines.push(`${ind}${indent}BackdropBackground "${frame.diskTexture}",`);
  }
  
  // Backdrop边框和装饰属性
  if (frame.backdropTileBackground) {
    lines.push(`${ind}${indent}BackdropTileBackground,`);
  }
  if (frame.backdropEdgeFile) {
    lines.push(`${ind}${indent}BackdropEdgeFile "${frame.backdropEdgeFile}",`);
  }
  if (frame.backdropCornerFlags) {
    lines.push(`${ind}${indent}BackdropCornerFlags "${frame.backdropCornerFlags}",`);
  }
  if (frame.backdropCornerSize !== undefined) {
    lines.push(`${ind}${indent}BackdropCornerSize ${formatNumber(frame.backdropCornerSize)},`);
  }
  if (frame.backdropBackgroundSize !== undefined) {
    lines.push(`${ind}${indent}BackdropBackgroundSize ${formatNumber(frame.backdropBackgroundSize)},`);
  }
  if (frame.backdropBackgroundInsets) {
    const insets = frame.backdropBackgroundInsets;
    lines.push(`${ind}${indent}BackdropBackgroundInsets ${formatNumber(insets[0])} ${formatNumber(insets[1])} ${formatNumber(insets[2])} ${formatNumber(insets[3])},`);
  }
  if (frame.backdropBlendAll) {
    lines.push(`${ind}${indent}BackdropBlendAll,`);
  }
  
  // 按钮特定属性  
  if (frame.tooltip && typeof frame.tooltip === 'string') {
    lines.push(`${ind}${indent}Tooltip "${escapeString(frame.tooltip)}",`);
  }
  
  // 子Frame（排除继承的子控件）
  if (frame.children && frame.children.length > 0) {
    // 过滤掉继承的子控件（它们已经在模板中定义）
    const inheritedIds = frame.fdfMetadata?.inheritedChildrenIds || [];
    const customChildren = frame.children.filter(childId => !inheritedIds.includes(childId));
    
    if (customChildren.length > 0) {
      lines.push('');
      customChildren.forEach(childId => {
        const childFrame = allFrames.find(f => f.id === childId);
        if (childFrame) {
          exportFrame(childFrame, allFrames, lines, indent, level + 1);
        }
      });
    }
  }
  
  // Frame定义结束
  lines.push(`${ind}}`);
}

/**
 * 导出锚点
 */
function exportAnchor(
  anchor: { point: FramePoint; relativeTo?: string; relativePoint?: FramePoint; x: number; y: number },
  allFrames: FrameData[],
  lines: string[],
  indent: string
): void {
  const pointStr = FramePoint[anchor.point];
  let line = `${indent}SetPoint ${pointStr}`;
  
  if (anchor.relativeTo) {
    // 将ID转换为Frame名称
    const relativeFrame = allFrames.find(f => f.id === anchor.relativeTo);
    const relativeName = relativeFrame ? relativeFrame.name : anchor.relativeTo;
    const relPointStr = anchor.relativePoint !== undefined ? FramePoint[anchor.relativePoint] : pointStr;
    line += `, "${relativeName}", ${relPointStr}`;
  }
  
  line += `, ${formatNumber(anchor.x)}, ${formatNumber(anchor.y)},`;
  lines.push(line);
}

/**
 * 检查是否使用SetAllPoints
 */
function checkSetAllPoints(anchors: any[]): boolean {
  if (anchors.length !== 2) return false;
  
  // 检查是否有TOPLEFT和BOTTOMRIGHT锚点
  const points = new Set(anchors.map(a => a.point));
  const hasTOPLEFT = points.has(FramePoint.TOPLEFT);
  const hasBOTTOMRIGHT = points.has(FramePoint.BOTTOMRIGHT);
  
  if (!hasTOPLEFT || !hasBOTTOMRIGHT) return false;
  
  // 检查两个锚点是否指向同一个relativeTo
  const relativeTo0 = anchors[0].relativeTo;
  const relativeTo1 = anchors[1].relativeTo;
  
  // 两者都没有relativeTo，或者都指向同一个
  return relativeTo0 === relativeTo1;
}

/**
 * 将FrameType枚举转换为FDF字符串
 */
function getFrameTypeString(type: FrameType): string {
  switch (type) {
    // 基础容器
    case FrameType.ORIGIN:
      return 'FRAME';
    case FrameType.FRAME:
      return 'FRAME';
    case FrameType.BACKDROP:
      return 'BACKDROP';
    case FrameType.SIMPLEFRAME:
      return 'SIMPLEFRAME';
    
    // 文本控件
    case FrameType.TEXT_FRAME:
      return 'TEXT';
    case FrameType.SIMPLEFONTSTRING:
      return 'SIMPLEFONTSTRING';
    case FrameType.TEXTAREA:
      return 'TEXTAREA';
    
    // 按钮控件
    case FrameType.BUTTON:
      return 'BUTTON';
    case FrameType.GLUETEXTBUTTON:
      return 'GLUETEXTBUTTON';
    case FrameType.GLUEBUTTON:
      return 'GLUEBUTTON';
    case FrameType.SIMPLEBUTTON:
      return 'SIMPLEBUTTON';
    case FrameType.BROWSER_BUTTON:
      return 'BROWSER_BUTTON';
    case FrameType.SCRIPT_DIALOG_BUTTON:
      return 'SCRIPT_DIALOG_BUTTON';
    case FrameType.INVIS_BUTTON:
      return 'INVIS_BUTTON';
    
    // 交互控件
    case FrameType.CHECKBOX:
      return 'CHECKBOX';
    case FrameType.EDITBOX:
      return 'EDITBOX';
    case FrameType.SLIDER:
      return 'SLIDER';
    case FrameType.SCROLLBAR:
      return 'SCROLLBAR';
    case FrameType.LISTBOX:
      return 'LISTBOX';
    case FrameType.MENU:
      return 'MENU';
    case FrameType.POPUPMENU:
      return 'POPUPMENU';
    
    // 图形控件
    case FrameType.SPRITE:
      return 'SPRITE';
    case FrameType.MODEL:
      return 'MODEL';
    case FrameType.HIGHLIGHT:
      return 'HIGHLIGHT';
    
    // 状态栏
    case FrameType.SIMPLESTATUSBAR:
      return 'SIMPLESTATUSBAR';
    case FrameType.STATUSBAR:
      return 'STATUSBAR';
    
    // 其他控件
    case FrameType.CONTROL:
      return 'CONTROL';
    case FrameType.DIALOG:
      return 'DIALOG';
    case FrameType.TIMERTEXT:
      return 'TIMERTEXT';
    
    default:
      return 'FRAME';
  }
}

/**
 * 格式化数字(保留合理的小数位)
 */
function formatNumber(num: number): string {
  // 保留6位小数,移除尾部的0
  const str = num.toFixed(6);
  return str.replace(/\.?0+$/, '');
}

/**
 * 转义字符串中的特殊字符
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

/**
 * 导出单个Frame到FDF(用于片段导出)
 */
export function exportFrameToFDF(frame: FrameData, allFrames: FrameData[], options: ExportOptions = {}): string {
  const { indent = '    ' } = options;
  const lines: string[] = [];
  
  exportFrame(frame, allFrames, lines, indent, 0);
  
  return lines.join('\n');
}
